/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

/**
 *
 * @author carol
 */
public class jTabbedTelas extends javax.swing.JFrame {
    
    private final Estoque telaEstoque;
    private final Funcionarios telaFuncionarios;
    private final Inicio telaInicio;
    private final telaMesa telaMesa;
    private final DashBoard DashBoard;


    public jTabbedTelas() {
        // Inicialização dos componentes
        initComponents();

        // Inicializar telas
        telaEstoque = new Estoque();
        telaFuncionarios = new Funcionarios();
        telaInicio = new Inicio();
        telaMesa = new telaMesa();
        DashBoard = new DashBoard(); // Certifique-se de que esta classe foi implementada
// Certifique-se de que esta classe foi implementada

        // Configurar abas
        configurarAbas();

        // Configurar cor de fundo
        getContentPane().setBackground(new java.awt.Color(39, 52, 105));

        // Listener para carregar dados ao trocar de aba
        configurarListeners();
    }

    private void configurarAbas() {
        // Adicionar telas às abas
        jTabbedPane1.addTab("Início", telaInicio.getContentPane());
        jTabbedPane1.addTab("Estoque", telaEstoque.getContentPane());
        jTabbedPane1.addTab("Funcionários", telaFuncionarios.getContentPane());
        jTabbedPane1.addTab("Mesa", telaMesa.getContentPane());
        jTabbedPane1.addTab("Dashboard", DashBoard.getContentPane());

    }

    private void configurarListeners() {
        jTabbedPane1.addChangeListener(e -> {
            int abaSelecionada = jTabbedPane1.getSelectedIndex();

            switch (abaSelecionada) {
                case 1 -> { // Aba Estoque
                    System.out.println("Carregando Estoque...");
                    telaEstoque.atualizaTabela(new dao.EstoqueDao()); // Atualizar a tabela do estoque
                }
                case 2 -> { // Aba Funcionários
                    telaFuncionarios.atualizaDashFuncionario(new dao.MesaDao());
                    telaFuncionarios.atualizarFuncionario(new dao.FuncionarioDao());
                }
                case 3 -> {
                 System.out.println("Carregando dados da mesa...");
                 telaMesa.atualizaMesas(new dao.MesaDao());
                 telaMesa.atualizarFuncionario(new dao.FuncionarioDao());
                 telaMesa.atualizaTabela(new dao.EstoqueDao());
                 }
                case 4 -> {
                    
                 System.out.println("Carregando dados do DashBoard...");
                 DashBoard.atualizaDashFuncionario(new dao.MesaDao());

                  
                }
                default -> System.out.println("Início selecionado.");
            }
        });
    }
    
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jTabbedTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jTabbedTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jTabbedTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jTabbedTelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jTabbedTelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
